development:
  uri: 'https://localhost:8443/taverna-server/'
  username:
  password:

test:
  uri: 'https://localhost:8443/taverna-server/'
  username:
  password:

production:
  uri: 'https://localhost:8443/taverna-server/'
  username:
  password:

